apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-hpa
servers: 1
agents: 2
image: rancher/k3s:v1.33.0-k3s1
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
ports:
  - port: "8080:3000"
    nodeFilters:
      - loadbalancer

