apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-monitoring
servers: 1
agents: 0
image: rancher/k3s:v1.33.0-k3s1
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
ports:
  - port: "9090:9090"            # Prometheus
    nodeFilters:
      - loadbalancer
  - port: "3000:80"              # Grafana
    nodeFilters:
      - loadbalancer
  - port: "16686:16686"          # Jaeger query
    nodeFilters:
      - loadbalancer
  - port: "14268:14268"          # Jaeger collector
    nodeFilters:
      - loadbalancer
  - port: "9411:9411"            # Zipkin endpoint for Jaeger
    nodeFilters:
      - loadbalancer
  - port: "9200:9200"            # Elasticsearch
    nodeFilters:
      - loadbalancer
