nameOverride: my-jaeger

allInOne:
  enabled: false

agent:
  enabled: true

collector:
  enabled: true
  service:
    type: LoadBalancer
    port: 14268
    targetPort: 14268
    zipkin:
      type: LoadBalancer
      port: 9411
      targetPort: 9411

query:
  enabled: true
  service:
    type: LoadBalancer
    port: 16686
    targetPort: 16686

provisionDataStore:
  cassandra: false
  elasticsearch: true

storage:
  type: elasticsearch

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "2Gi"

  service:
    type: LoadBalancer
    port: 9200
    targetPort: 9200

  extraEnvVars:
    - name: ES_JAVA_OPTS
      value: "-Xms1g -Xmx1g"

  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
