prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

  service:
    type: LoadBalancer

grafana:
  service:
    type: LoadBalancer

  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
      searchNamespace: ALL
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true

  additionalDataSources:
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-my-jaeger-query.monitoring.svc.cluster.local:16686
      isDefault: false
      uid: jaeger
