apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kourier-envoy
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: 3scale-kourier-gateway
  namespaceSelector:
    matchNames:
      - kourier-system
  endpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 30s
