
# monitoring/values-remote-write.yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'all-services'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+);(.+)
        replacement: $2

remote_write:
  - url: "http://host.k3d.internal:9090/api/v1/write"
